feat: allow returning multiple directories
WilliamVenner/steamlocate-rs pull request #64
Opened 2024-03-27 18:39 UTC by LuisMayo

This PR adds the ability for the library to locate many valid installations, which may be useful, specially on Linux installations. As discussed here: https://github.com/WilliamVenner/steamlocate-rs/issues/17#issuecomment-1950298930

I'm really a newbie when it comes to Rust so I'd be happy to fix any problems you may encounter and thanks for your work!

2024-04-13 15:05 UTC, amtep commented
Just wanted to let you know that I'm also waiting for this feature :)

My use case is that I want to find a particular game, regardless of in which installation it's installed.
So I'll loop over the steamdirs until the find_app resolves.

I looked at the code and wondered, is it really an error if no installations are found? I figure it could just return an empty Vec in that case.

2024-04-13 15:51 UTC, LuisMayo commented
> Just wanted to let you know that I'm also waiting for this feature :)
> 
> My use case is that I want to find a particular game, regardless of in which installation it's installed. So I'll loop over the steamdirs until the find_app resolves.
> 
> I looked at the code and wondered, is it really an error if no installations are found? I figure it could just return an empty Vec in that case.

That's actually the very same reason I want it. My app patches a Videogame (VHS) and I want to locate it to patch the exe, no matter the install dir

About returning on Error I just made it to be consistent with the `locate` function, but it's true that it may not make that much sense, so I could change it to return an empty array, I don't have strong feelings towards any of the options.

2025-02-10 03:46 UTC, dotaxis commented
I would love to have this merged. I'm building a project and would like to account for edge cases where people may have both Flatpak and Native Steam installed and I want to let them pick which installation to work with.

I will just use your fork for now. Thank you!

2025-02-10 05:59 UTC, LuisMayo commented
I see the branch is now conflicting with main. If I get any signal this is wanted I will rebase!

And you can use the fork of course. I've been doing that and it works for me

2025-02-10 06:24 UTC, dotaxis commented
Unfortunately I wasn't able to use it in my case because it returned multiple entries for each installation, as per these lines:
https://github.com/WilliamVenner/steamlocate-rs/blob/f69067b6f9a6769f9255a0d0c4388d70e0402b83/src/locate.rs#L74-L86

In my experience the `.steam/root` symlink always exists, but I don't have a huge variety of environments to be sure of that. It would be great to have some logic which makes locate_multiple only return one entry per native/flatpak/steam installation, but since I'm not currently looking to support snaps in my project, I just wrote out a function to test for the `.steam/root` locations and use `from_dir()` to convert them to SteamDir.

IMO, only a crazy person would have multiple installations of Steam on the same machine, but I can't count on other people to not be crazy, so I'm still very interested in this PR.

This crate has been an absolute lifesaver and other than this very minor limitation, it's perfect.

2025-02-11 23:31 UTC, CosmicHorrorDev commented
Sorry for the (very long) delay. I'm finally getting around to taking a look at this and in general I like the idea of providing an API for locating all steam installations. One caveat though; I would also really like to be able to detect when a steam installation is still actually valid (ref #17). Most of the time it seems like people have multiple installations from installing and uninstalling in different ways that leave lingering files that we pick up as a steam installation. I'd prefer if we could filter out no-longer-valid installations in some way

Re @amtep 

> I looked at the code and wondered, is it really an error if no installations are found? I figure it could just return an empty Vec in that case.

I would agree. Returning an empty vec when trying to locate all installations seems reasonable to me

Re @dotaxis 

> In my experience the .steam/root symlink always exists

I can confirm the same on my installation. Both `~/.steam/steam` and `~/.steam/root` are both symlinks to the same installation. I'm also equally unsure if this is always the case or if we should be preferring one or the other. It's possible that we could just remove one and leave the other :thinking: 

---

Also thanks for all the kind words! It's been a lot of effort trying to juggle all of the projects I try to maintain, but knowing that other people get use out of them makes all the work worth it :)

2025-02-11 23:48 UTC, dotaxis commented
> I can confirm the same on my installation. Both `~/.steam/steam` and `~/.steam/root` are both symlinks to the same installation. I'm also equally unsure if this is always the case or if we should be preferring one or the other. It's possible that we could just remove one and leave the other 🤔

I can't find any documentation on what the different symlinks are meant to point to but I think it is safe to remove `.local/share/Steam`

But perhaps a better approach would be to actually follow the symlinks and then form a vector of install directories based on where they point to. That would avoid duplicates without just guessing at which symlinks are important.

2025-02-11 23:56 UTC, CosmicHorrorDev commented
> But perhaps a better approach would be to actually follow the symlinks and then form a vector of install directories based on where they point to. That would avoid duplicates without just guessing at which symlinks are important.

That seems like it might be the most robust approach. It should just involve a little [`std::fs::read_link`](https://doc.rust-lang.org/std/fs/fn.read_link.html) logic

2025-02-15 07:19 UTC, dotaxis commented
@LuisMayo do you have any interest in implementing this using read_link to avoid dupes?

2025-02-15 10:22 UTC, LuisMayo commented
I will implement Link following as well as other of the suggestions here (like empty Vec)

I'm gonna have a really busy week so it may take a while even those two little changes

2025-02-15 10:42 UTC, CosmicHorrorDev commented
Just ping me whenever your changes are ready. Now that v2 is released I'm much more available for review :)

2025-02-15 20:26 UTC, LuisMayo commented
Hi

Changes pushed @CosmicHorrorDev 

Please someone check if Windows side of things is working fine since I haven't had the time to do it

Thanks!

2025-02-15 20:52 UTC, CosmicHorrorDev commented
Clippy will probably be angry, but that's what CI is for after all 😸

2025-02-16 17:07 UTC, LuisMayo commented
I think clippy should be happy now

2025-02-16 17:33 UTC, CosmicHorrorDev commented
`cargo clippy --fix` may make things a bit easier btw. I'm not sure if it handles `cfg`s outside of what you're doing, but it's a bit easier than manually fixing everything

2025-02-16 17:33 UTC, LuisMayo commented
Ok more changes now. Let's see if it works

2025-02-16 17:37 UTC, CosmicHorrorDev commented
Also another quick tip: I think you can enable action runs on your fork to get a bit of a faster feedback loop

2025-02-16 18:02 UTC, LuisMayo commented
Finally. Sorry for the trouble

2025-02-16 18:18 UTC, CosmicHorrorDev requested changes
Just a few nits, but overall the implementation is looking pretty good now 🚀

2025-02-16 18:18 UTC, CosmicHorrorDev commented on src/lib.rs
> +        Self::from_dir(&paths[0])
This got changed from returning a `ValidationError` for a missing directory to panicking when missing. You can get the old behavior back with something like

```rust
let path = paths.get(0).ok_or_else(/* missing dir validation error */)?;
Self::from_dir(&path)
```

2025-02-16 18:18 UTC, CosmicHorrorDev commented on src/lib.rs
> +        mapped_paths
```suggestion
        paths.iter().map(Self::from_dir).collect()
```

Small cleanup

2025-02-16 18:18 UTC, CosmicHorrorDev commented on src/locate.rs
> +    return locate_steam_dir_helper();
```suggestion
    locate_steam_dir_helper()
```

I think this can have the explicit return dropped

2025-02-16 18:18 UTC, CosmicHorrorDev commented on src/locate.rs
> +    }
```suggestion
    locate_steam_dir_helper().map(|path| vec![path])
```

Slightly more succinct

2025-02-16 18:18 UTC, CosmicHorrorDev commented
> Finally. Sorry for the trouble

No worries at all! I'm just happy to have help :D

2025-02-22 16:28 UTC, LuisMayo commented
Hi @CosmicHorrorDev 

I've updated the PR according to your suggestions

Thanks a lot!

2025-02-22 16:42 UTC, LuisMayo commented
Hi @CosmicHorrorDev 

Suggestions applied!

Thanks a lot

2025-02-23 21:31 UTC, CosmicHorrorDev approved these changes
I went ahead and pushed a commit that switches things back to maintaining the original order that dirs get returned in while deduping with a `BTreeSet` instead of sorting and deduping, so that way we keep the same order that things are returned in as `main` (aka makes me comfortable releasing this without having to consider it a breaking change)

2025-02-23 21:33 UTC, CosmicHorrorDev commented
@LuisMayo It looks like there are some merge conflicts. I can handle them if you don't want to deal with them, but I can also leave it to you of course

2025-02-23 21:37 UTC, LuisMayo commented
I can deal with them but I won't be able to in the following days!

Thanks for the commit preserving the ordering btw.

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
From: CosmicHorror ***@***.***>
Sent: Sunday, February 23, 2025 10:34:15 PM
To: WilliamVenner/steamlocate-rs ***@***.***>
Cc: Luis Mayo Valbuena ***@***.***>; Mention ***@***.***>
Subject: Re: [WilliamVenner/steamlocate-rs] feat: allow returning multiple directories (PR #64)


@LuisMayo<https://github.com/LuisMayo> It looks like there are some merge conflicts. I can handle them if you don't want to deal with them, but I can also leave it to you of course

—
Reply to this email directly, view it on GitHub<https://github.com/WilliamVenner/steamlocate-rs/pull/64#issuecomment-2677128783>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AE2K4BFJIUDJBFZ2FTC5NOL2RI5FPAVCNFSM6AAAAABWZS3TOSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMNZXGEZDQNZYGM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

[CosmicHorrorDev]CosmicHorrorDev left a comment (WilliamVenner/steamlocate-rs#64)<https://github.com/WilliamVenner/steamlocate-rs/pull/64#issuecomment-2677128783>

@LuisMayo<https://github.com/LuisMayo> It looks like there are some merge conflicts. I can handle them if you don't want to deal with them, but I can also leave it to you of course

—
Reply to this email directly, view it on GitHub<https://github.com/WilliamVenner/steamlocate-rs/pull/64#issuecomment-2677128783>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AE2K4BFJIUDJBFZ2FTC5NOL2RI5FPAVCNFSM6AAAAABWZS3TOSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMNZXGEZDQNZYGM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2025-03-02 17:58 UTC, LuisMayo commented
No merge conflicts here!

2025-03-06 06:14 UTC, CosmicHorrorDev approved these changes
Looks great, thanks!

2025-03-06 06:15 UTC, merged